version: "3.8"
services:
  postgres-bot:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "pgdata_bot:/var/lib/postgresql/data"
    command:
      [
        "postgres",
        "-c",
        "log_statement=mod",
        "-c",
        "log_min_error_statement=ERROR",
      ]
  uni-bot:
    build: .
    image: "ghcr.io/reecedonovan/uni-bot:latest"
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_APP: ${DISCORD_APP}
      DISCORD_GUILD: ${DISCORD_GUILD}
      CANVAS_DOMAIN: ${CANVAS_DOMAIN}
      CANVAS_TERM: ${CANVAS_TERM}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./:/go/src/app
    depends_on:
      - postgres-bot
volumes:
  pgdata_bot:
