version: "3.8"
services:
  discord-bot:
    build:
      context: ./
      target: builder
    image: uni-bot/discord-bot
    env_file: ./.env
    environment:
      - ENV=dev
    volumes:
      - ./:/go/src/app
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"

    # TODO: Backend database?
