version: "3.8"
services:
  postgres-bot:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - "pgdata_bot:/var/lib/postgresql/data"
    command:
      [
        "postgres",
        "-c",
        "log_statement=mod",
        "-c",
        "log_min_error_statement=ERROR",
      ]
  uni-bot:
    build: .
    image: "ghcr.io/reecedonovan/uni-bot:latest"
    volumes:
      - ./:/go/src/app
    depends_on:
      - postgres-bot
volumes:
  pgdata_bot:
