# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Ensure latest version of git.
      - name: Ensure latests version of git
        run: |
          sudo apt-get install -y software-properties-common \
          && sudo apt-get update \
          && sudo add-apt-repository -y ppa:git-core/ppa \
          && sudo apt-get update \
          && sudo apt-get install -y git

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Builds docker images and pushes them to GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push prod image
        uses: docker/build-push-action@v2.7.0
        with:
          push: true
          context: .
          tags: ghcr.io/reecedonovan/uni-bot:latest, ghcr.io/reecedonovan/uni-bot:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: deploy to Netsoc Cloud via SSH Action
        uses: appleboy/ssh-action@master
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_APP: ${{ secrets.DISCORD_APP }}
          DISCORD_GUILD: ${{ secrets.DISCORD_GUILD }}
          CANVAS_DOMAIN: ${{ secrets.CANVAS_DOMAIN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          port: ${{ secrets.PORT }}
          envs: DISCORD_TOKEN, DISCORD_APP, DISCORD_GUILD, CANVAS_DOMAIN, DB_HOST, DB_PORT, DB_USER, DB_PASS, DB_NAME
          script: |
            cd /root/'uni-bot'
            git pull
            docker-compose pull
            export DISCORD_TOKEN=$DISCORD_TOKEN 
            export DISCORD_APP=$DISCORD_APP 
            export DISCORD_GUILD=$DISCORD_GUILD 
            export CANVAS_DOMAIN=$CANVAS_DOMAIN 
            export DB_HOST=$DB_HOST 
            export DB_PORT=$DB_PORT 
            export DB_USER=$DB_USER 
            export DB_PASS=$DB_PASS 
            export DB_NAME=$DB_NAME 
            docker-compose up -d
